### ISSUE TITLE
Feature Request: Upload progress indicator

### ISSUE THREAD

**Issue by designbureau** [elhardoum/AJAX-File-Upload#1]
Hi

Love your plugin! 
It would be useful for users to show an upload progress indicator such as a progress bar. Any thoughts on how this might be achieved with this plugin?

**Comment by elhardoum** [comment]
Hey,

Thanks!

There are many ways to achieve this, I suggest adding this code 

https://gist.github.com/elhardoum/22e4ae0f2bca905f88a89d9b2f056713

right before any `$.ajax` properties in [assets/js/main.js](https://github.com/elhardoum/AJAX-File-Upload/blob/master/assets/js/main.js#L128) file.

Hope that helps.
Thanks,
Samuel
